// <auto-generated />
using Arcade_Game;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arcade_Game.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260708222152_AddPlayerItemsTable")]
    partial class AddPlayerItemsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Arcade_Game.PlayerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("Arcade_Game.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalGoldCoinValues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSilverCoinValues")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("Arcade_Game.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Category = "Skin",
                            CurrencyType = 1,
                            Name = "Spaceship 2",
                            Price = 500
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bullet",
                            CurrencyType = 0,
                            Name = "Green Bullets",
                            Price = 300
                        },
                        new
                        {
                            Id = 1,
                            Category = "Theme",
                            CurrencyType = 1,
                            Name = "Neon Background",
                            Price = 400
                        },
                        new
                        {
                            Id = 4,
                            Category = "Consumable",
                            CurrencyType = 0,
                            Name = "Extra Life",
                            Price = 150
                        });
                });

            modelBuilder.Entity("Arcade_Game.PlayerItem", b =>
                {
                    b.HasOne("Arcade_Game.PlayerProfile", "PlayerProfile")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arcade_Game.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("Arcade_Game.PlayerProfile", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
