// <auto-generated />
using Arcade_Game;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arcade_Game.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Arcade_Game.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraLives")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalGoldCoinValues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSilverCoinValues")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("Arcade_Game.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Skin",
                            CurrencyType = 1,
                            IsEquipped = false,
                            IsPurchased = false,
                            Name = "Spaceship 2",
                            Price = 500
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bullet",
                            CurrencyType = 0,
                            IsEquipped = false,
                            IsPurchased = false,
                            Name = "Green Bullets",
                            Price = 300
                        },
                        new
                        {
                            Id = 3,
                            Category = "Theme",
                            CurrencyType = 1,
                            IsEquipped = false,
                            IsPurchased = false,
                            Name = "Neon Background",
                            Price = 400
                        },
                        new
                        {
                            Id = 4,
                            Category = "Consumable",
                            CurrencyType = 0,
                            IsEquipped = false,
                            IsPurchased = false,
                            Name = "Extra Life",
                            Price = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
